### PR TITLE
Feature/ticket 15 edit comment single post

### PR DESCRIPTION
**Pull request by seintun**
The PUT feature for editing comment inside the post

### CODE REVIEW

**Review by Tyler-Pritchard — APPROVED** [review]

**Comment by fantasticThingsToCome** [comment]
tested on Postman

**Review by Tyler-Pritchard — DISMISSED** [review]
Tested in Postman

**Review by Tyler-Pritchard — COMMENTED** [review]
test

**Comment by seintun** [comment]
File missing to be merged. PR request deleted

**Pull request closed without merging**
